In [5]:
import numpy as np
import numpy
import pandas as pd
import pandas

In [3]:
print('Task 1:')  
print(pd.__version__)

Task 1:
1.5.2


In [168]:
print('Task 2:')
dtype = [('col1','int32'), ('col2','float32'), ('col3','float32')]
#dtype shows the desired array type
values = numpy.zeros(2, dtype=dtype)
print(values)
index = ['Row_'+str(i) for i in range(1, len(values)+1)]
#print(index)

df = pandas.DataFrame(values)
print(df)

df = pandas.DataFrame(values)
#print(df)

Task 2:
[(0, 0., 0.) (0, 0., 0.)]
   col1  col2  col3
0     0   0.0   0.0
1     0   0.0   0.0


In [12]:
print('Task 3:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.iloc[:4]) 

Task 3:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0


In [169]:
print('Task 4:')
values = np.random.randint(150, 210, size=6)
print(values)

Task 4:
[198 208 156 164 196 190]


In [27]:
print('task 5:')
values = np.random.randint(10, 30,size = (4,2))
dataframe = pd.DataFrame(values,columns=list('AB'))
print(dataframe)

task 5:
    A   B
0  16  19
1  10  26
2  14  21
3  14  27


In [32]:
print('Task 6:')
values =np.random.randint(120, 340, size=(5, 4))
dataframe = pd.DataFrame(values, columns=['A', 'B', 'C', 'D'])
print(dataframe)

Task 6:
     A    B    C    D
0  120  329  315  142
1  121  329  212  183
2  186  248  283  339
3  191  309  122  324
4  168  206  338  265


In [34]:
print("task 7")
values = np.random.randint(1,100,size =(4,5))
print(values)

task 7
[[ 5 78 20 99 22]
 [38 53 77 87 56]
 [11 90 23 17 87]
 [25 64 16 87 57]]


In [38]:
print ("task 8")
values = np.random.randint(100,size = (2,5))
df = pd.DataFrame(values ,columns =list('ABCDE'))
print(df)

task 8
    A   B   C   D   E
0  58  55  86  76  80
1  95  55  34  52  19


In [43]:
print("task 9"),
values = np.zeros((3,2))
df = pd.DataFrame(values ,columns = list('xy'))
print(df)

task 9
     x    y
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0


In [53]:
print("task 10")
dtype = [('math','int32'),('science','int32')]
values = np.random.randint(50,100,size =(10,2))
index = [dtype[i][0] for i  in range(len(dtype))]
print(index)
df =pd.DataFrame(values,columns = index)
print(df)

task 10
['math', 'science']
   math  science
0    99       54
1    94       57
2    69       55
3    87       76
4    96       88
5    55       50
6    88       67
7    79       84
8    93       74
9    50       92


In [54]:
print('Task 11:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.head())

Task 11:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0
4  8  6    mar  fri  91.7  33.3   77.5    9   8.3  97     4   0.2     0


In [57]:
print('Task 13:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0:4,0:5])


Task 13:
   0  1      2    3     4
0  X  Y  month  day  FFMC
1  7  5    mar  fri  86.2
2  7  4    oct  tue  90.6
3  7  4    oct  sat  90.6


In [60]:
print('Task 14:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0::2,0:5])

Task 14:
     0  1      2    3     4
0    X  Y  month  day  FFMC
2    7  4    oct  tue  90.6
4    8  6    mar  fri  91.7
6    8  6    aug  sun  92.3
8    8  6    aug  mon  91.5
..  .. ..    ...  ...   ...
508  2  4    aug  fri    91
510  5  4    aug  fri    91
512  8  6    aug  sun  81.6
514  2  4    aug  sun  81.6
516  1  4    aug  sat  94.4

[259 rows x 5 columns]


In [74]:
print('Task 15:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
print(df1)
df['total'] = df1.sum(axis=1)
print(df)

Task 14:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
   language  science  maths  history
0        90       56     34       34
1        10       34     32       67
2        90       23     12       32
3        20       67     90       45
4        30       56     45       65
5        90       45     45       34
6        50       90     45       23
  student  language  science  maths  history  total
0   kumar        90       56     34       34    214
1   kevin        10       34     32       67    143
2   sammy        90       23     12       32    157
3  janice        20       67     90       45    222
4   peter        30       56     45       65    196
5    prem        90    

In [171]:
print('Task 16:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df[df.maths>40]
print(df1)

Task 16:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [80]:
print('Task 17:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.query('language>=50')
print(df1)

Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
2   sammy        90       23     12       32
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [81]:
print('Task 18:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df)


Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4    prem        90       45     45       34
5  carrol        50       90     45       23


In [82]:
print('Task 19:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [1,2,5])
print(df)


Task 17:
  student  language  science  maths  history
0   sammy        90       23     12       32
1  janice        20       67     90       45
2    prem        90       45     45       34
3  carrol        50       90     45       23


In [83]:
print('Task 20:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df.columns[3])


Task 17:
maths


In [84]:
print('Task 21:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [0])
print(df)

Task 18:
    kumar  90  56  34  34.1
0   kevin  10  34  32    67
1   sammy  90  23  12    32
2  janice  20  67  90    45
3   peter  30  56  45    65
4    prem  90  45  45    34
5  carrol  50  90  45    23


In [173]:
print('Task 22:')
from io import StringIO

s = """
        X,Y
        10, 21,23
        32, 44,34
        52, 63,56
    """

df = pd.read_csv(StringIO(s))

print(df.shape)
print(df)

Task 22:
(3, 2)
            X   Y
10         21  23
32         44  34
52         63  56


In [100]:
print('Task 23:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)
print(df)
df['min']= df1.min(axis=1)
print(df)
df['sum'] = df1.sum(axis=1)
print(df)
df['average'] = df1.mean(axis=1).astype(int)
print(df)

Task 23:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max
0   kumar        90       56     34       34   90
1   kevin        10       34     32       67   67
2   sammy        90       23     12       32   90
3  janice        20       67     90       45   90
4   peter        30       56     45       65   65
5    prem        90       45     45       34   90
6  carrol        50       90     45       23   90
  student  language  science  maths  history  max  min
0   kumar        90       56     34       34   90   34
1   kevin        10       34     32       67   67   10
2   sammy        90       23     12       32   90   12
3  janice  

In [103]:
print('Task 24:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)

df['min']= df1.min(axis=1)

df['sum'] = df1.sum(axis=1)
df['average'] = df1.mean(axis=1).astype(int)
def math1(row):
    return (row.maths*2)
df['math_special'] = df1.apply(math1,axis=1).astype(int)
print(df)

Task 23:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max  min  sum  average  \
0   kumar        90       56     34       34   90   34  214       53   
1   kevin        10       34     32       67   67   10  143       35   
2   sammy        90       23     12       32   90   12  157       39   
3  janice        20       67     90       45   90   20  222       55   
4   peter        30       56     45       65   65   30  196       49   
5    prem        90       45     45       34   90   34  214       53   
6  carrol        50       90     45       23   90   23  208       52   

   math_special  
0            68  
1            64  


In [118]:
print('Task 25:') 
def pass_one_subject(row):
    if(row.maths >=45):
        return 'Pass'
    if(row.language > 40 and row.science > 44):
        return 'Pass'
    
    return 'Fail' 

df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)

df['min']= df1.min(axis=1)

df['sum'] = df1.sum(axis=1)
df['average'] = df1.mean(axis=1).astype(int)
def math1(row):
    return (row.maths*2)
#function will return string 
df['pass'] = df1.apply(pass_one_subject,axis=1)
print(df)


Task 25:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max  min  sum  average  pass
0   kumar        90       56     34       34   90   34  214       53  Pass
1   kevin        10       34     32       67   67   10  143       35  Fail
2   sammy        90       23     12       32   90   12  157       39  Fail
3  janice        20       67     90       45   90   20  222       55  Pass
4   peter        30       56     45       65   65   30  196       49  Pass
5    prem        90       45     45       34   90   34  214       53  Pass
6  carrol        50       90     45       23   90   23  208       52  Pass


In [110]:
print('Task 26:') 
df = pandas.read_csv('abc2.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis =1)
df.fillna(df1.mean(),inplace =True)
print(df)


Task 26:
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0    NaN       34
6  carrol        50     90.0   45.0       23
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10     54.0   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20     54.0   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0   43.0       34
6  carrol        50     90.0   45.0       23


In [116]:
print('Task 27:')
df = pd.DataFrame(np.random.randint(20 ,40, size=(10,5)))
df.iloc[0::2, 0:2] = np.nan 
print(df)
df.loc[:, 'test'] = df.iloc[:, 2:].sum(axis=1)
print(df)

Task 27:
      0     1   2   3   4
0   NaN   NaN  35  26  29
1  23.0  21.0  36  35  39
2   NaN   NaN  32  38  27
3  27.0  26.0  25  21  33
4   NaN   NaN  20  21  22
5  25.0  24.0  38  26  20
6   NaN   NaN  37  26  30
7  38.0  29.0  35  20  29
8   NaN   NaN  27  30  31
9  28.0  24.0  30  31  33
      0     1   2   3   4  test
0   NaN   NaN  35  26  29    90
1  23.0  21.0  36  35  39   110
2   NaN   NaN  32  38  27    97
3  27.0  26.0  25  21  33    79
4   NaN   NaN  20  21  22    63
5  25.0  24.0  38  26  20    84
6   NaN   NaN  37  26  30    93
7  38.0  29.0  35  20  29    84
8   NaN   NaN  27  30  31    88
9  28.0  24.0  30  31  33    94


In [117]:
print('Task 28:') 
df = pandas.read_csv('score.csv', sep=',', encoding = "ISO-8859-1")
print(df.shape) 

Task 28:
(16, 5)


In [134]:
print('Task 29:')
df = pd.DataFrame(np.random.randint(20 ,40, size=(10,5)),columns=list('ABCDE'))
print(df)
df.iloc[0::2, 0:2] = np.nan 
print(df)
#inplace == True it changes the original dataframe
df1=df.fillna(df.mean() ,inplace =False)
print(df1)
print(df)


Task 29:
    A   B   C   D   E
0  24  26  30  22  22
1  22  22  27  23  29
2  35  34  39  22  25
3  33  25  37  20  21
4  24  22  26  36  28
5  21  26  27  39  39
6  36  20  30  38  29
7  29  26  34  32  30
8  39  39  22  23  34
9  34  28  39  31  20
      A     B   C   D   E
0   NaN   NaN  30  22  22
1  22.0  22.0  27  23  29
2   NaN   NaN  39  22  25
3  33.0  25.0  37  20  21
4   NaN   NaN  26  36  28
5  21.0  26.0  27  39  39
6   NaN   NaN  30  38  29
7  29.0  26.0  34  32  30
8   NaN   NaN  22  23  34
9  34.0  28.0  39  31  20
      A     B   C   D   E
0  27.8  25.4  30  22  22
1  22.0  22.0  27  23  29
2  27.8  25.4  39  22  25
3  33.0  25.0  37  20  21
4  27.8  25.4  26  36  28
5  21.0  26.0  27  39  39
6  27.8  25.4  30  38  29
7  29.0  26.0  34  32  30
8  27.8  25.4  22  23  34
9  34.0  28.0  39  31  20
      A     B   C   D   E
0   NaN   NaN  30  22  22
1  22.0  22.0  27  23  29
2   NaN   NaN  39  22  25
3  33.0  25.0  37  20  21
4   NaN   NaN  26  36  28
5  21.0  26.0  27  39

In [141]:
print('Task 30:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df[-4:])

Task 30:
    0  1    2    3     4     5      6     7     8   9    10 11     12
514  2  4  aug  sun  81.6  56.7  665.6   1.9  21.9  71  5.8  0  54.29
515  7  4  aug  sun  81.6  56.7  665.6   1.9  21.2  70  6.7  0  11.16
516  1  4  aug  sat  94.4   146  614.7  11.3  25.6  42    4  0      0
517  6  3  nov  tue  79.5     3  106.7   1.1  11.8  31  4.5  0      0


In [139]:
print('Task 31:')
import functools
series1 = pd.Series([i / 100.0 for i in range(1,6)])
print(series1)
def CumRet(x,y):
    return x +(1 + y)
def Red(x):
    return functools.reduce(CumRet,x,1.0)
s2 = series1.expanding().apply(Red)

print(s2)

Task 31:
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    2.01
1    3.03
2    4.06
3    5.10
4    6.15
dtype: float64


In [145]:
print('Task 32:')
df = pandas.read_csv('forestfires.csv', sep=',')
print(df[-4:-1])

Task 30:
     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00


In [143]:
print('Task 33:')
df = pandas.read_csv('forestfires.csv', sep=',')
print(df[2:4])

Task 30:
   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0


In [146]:
print('Task 34:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.iloc[1:9])

Task 34:
  0  1    2    3     4      5      6     7     8   9    10   11 12
1  7  5  mar  fri  86.2   26.2   94.3   5.1   8.2  51  6.7    0  0
2  7  4  oct  tue  90.6   35.4  669.1   6.7    18  33  0.9    0  0
3  7  4  oct  sat  90.6   43.7  686.9   6.7  14.6  33  1.3    0  0
4  8  6  mar  fri  91.7   33.3   77.5     9   8.3  97    4  0.2  0
5  8  6  mar  sun  89.3   51.3  102.2   9.6  11.4  99  1.8    0  0
6  8  6  aug  sun  92.3   85.3    488  14.7  22.2  29  5.4    0  0
7  8  6  aug  mon  92.3   88.9  495.6   8.5  24.1  27  3.1    0  0
8  8  6  aug  mon  91.5  145.4  608.2  10.7     8  86  2.2    0  0


In [158]:
print('Task 36:')  
def xrange(x):
    return iter(range(x))
import random as rn
rnd_1  =  [ rn.randrange ( 1 , 200 )  for  _  in  range ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 200 )  for  _  in  range ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 200)  for  _ in  range ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'random_1' :  rnd_1 ,  'random_2' :  rnd_2 ,  'random_3' :  rnd_3 })

print(data)

Task 36:
1000
          date  random_1  random_2  random_3
0   2012-04-10       163        66        40
1   2012-04-11       151       185        85
2   2012-04-12       154       180        32
3   2012-04-13       134        81        32
4   2012-04-14       160       130       142
..         ...       ...       ...       ...
995 2014-12-31       105       120        34
996 2015-01-01        17       146       198
997 2015-01-02       120        64        67
998 2015-01-03       126        60        45
999 2015-01-04       195        56        28

[1000 rows x 4 columns]


In [159]:
print('Task 37:')
below_15 = data[data['random_1'] < 20]    
print(below_50)

Task 37:
          date  rnd_1  rnd_2  rnd_3
29  2012-05-09     17     50    143
52  2012-06-01     18     63    196
56  2012-06-05     18     29     69
64  2012-06-13      8    184    138
65  2012-06-14     16    142     16
..         ...    ...    ...    ...
966 2014-12-02     10    154    129
975 2014-12-11     12     67    177
979 2014-12-15     13     38     12
989 2014-12-25      7     65    110
999 2015-01-04      6    156     99

[93 rows x 4 columns]


In [162]:
five_to_ten = data[(data['random_1']>=5 )& (data['random_1']<10)]
print(five_to_ten) 

          date  random_1  random_2  random_3
55  2012-06-04         6       158       138
84  2012-07-03         5       122         2
101 2012-07-20         6       177       112
106 2012-07-25         5       124        48
112 2012-07-31         5       197        21
248 2012-12-14         6         8       150
267 2013-01-02         6       165        16
384 2013-04-29         5       134         9
385 2013-04-30         6        82       170
403 2013-05-18         8       136        88
408 2013-05-23         5        12       180
458 2013-07-12         6       138        30
475 2013-07-29         7       163        35
495 2013-08-18         5       143       116
513 2013-09-05         6       112       148
528 2013-09-20         8        86       124
538 2013-09-30         9       128        55
558 2013-10-20         7        48        86
583 2013-11-14         7        34         5
592 2013-11-23         8        37         7
599 2013-11-30         7        91       118
621 2013-1

In [163]:
print('Task 39:')  
fifteen_to_20 = data[(data['random_1']>=15 )& (data['random_1']<20)]
print(fifteen_to_20)

Task 39:
          date  random_1  random_2  random_3
58  2012-06-07        15        84       199
75  2012-06-24        19        16        22
151 2012-09-08        15        22        72
206 2012-11-02        18       187       163
207 2012-11-03        16       148        97
261 2012-12-27        15       110        60
296 2013-01-31        18       121        35
399 2013-05-14        15       128       187
432 2013-06-16        19       100       136
574 2013-11-05        17       143        42
629 2013-12-30        15        42        68
644 2014-01-14        17       197       156
760 2014-05-10        18       146       118
867 2014-08-25        19       166       100
920 2014-10-17        16        79        60
931 2014-10-28        17       146       132
996 2015-01-01        17       146       198


In [164]:
print('Task 40:')  
fifteen_to_20 = data[(data['random_1']>=15 )& (data['random_1']<33)]
print(fifteen_to_20)

Task 40:
          date  random_1  random_2  random_3
16  2012-04-26        24        11        92
33  2012-05-13        30        21       105
46  2012-05-26        27       119       158
58  2012-06-07        15        84       199
75  2012-06-24        19        16        22
..         ...       ...       ...       ...
948 2014-11-14        27        70        27
964 2014-11-30        24       155       139
970 2014-12-06        32        23       142
977 2014-12-13        29       108       134
996 2015-01-01        17       146       198

[77 rows x 4 columns]


In [167]:
print('TASK 41:')
date = pd.date_range('2022-01-01','2022-12-03')
n = len(date)
def fillrange(start,end,count):
    return [rn.randrange(start,end) for _ in range(count)] 
random_1 = fillrange(10,30,n)
random_2 = fillrange(10,50,n)
random_3 = fillrange(10,40,n)
data = pd.DataFrame({'date':date,'random_1':random_1,'random_2':random_2,'random_3':random_3})
print(data)

TASK 41:
          date  random_1  random_2  random_3
0   2022-01-01        20        12        24
1   2022-01-02        15        13        17
2   2022-01-03        26        38        38
3   2022-01-04        16        40        17
4   2022-01-05        18        25        17
..         ...       ...       ...       ...
332 2022-11-29        15        24        18
333 2022-11-30        20        28        31
334 2022-12-01        25        43        34
335 2022-12-02        24        20        22
336 2022-12-03        28        25        24

[337 rows x 4 columns]


In [174]:
print('Task 42')
date = data.set_index('date')
print(date.head())

Task 42
            random_1  random_2  random_3
date                                    
2022-01-01        20        12        24
2022-01-02        15        13        17
2022-01-03        26        38        38
2022-01-04        16        40        17
2022-01-05        18        25        17


In [205]:
print('Task 43:') 
df = pd.DataFrame({
    'A' : [10,20,30,40], 
    'B' : [90,80,70,60],
    'C' : [110,120,130,140]
})
print(df) 

print('changing on one column')
# Change columns
df.loc[df.A >= 20,'B'] = 45
print(df)

Task 43:
    A   B    C
0  10  90  110
1  20  80  120
2  30  70  130
3  40  60  140
changing on one column
    A   B    C
0  10  90  110
1  20  45  120
2  30  45  130
3  40  45  140


In [207]:
print('Task 44:')  
print('changing on multipe columns')
df.loc[df.A > 2,['B', 'C']] = [(35),25]
print(df)

Task 44:
changing on multipe columns
    A   B   C
0  10  35  25
1  20  35  25
2  30  35  25
3  40  35  25


In [211]:
print('Task 45:') 
filter = df['A'] > 20
print(df.where(filter,[10,20,30]))

Task 45:
    A   B   C
0  10  20  30
1  10  20  30
2  30  35  25
3  40  35  25


In [213]:
print('Task 46:')
print(df)  
df['logic'] = np.where(df['A'] > 20, 'High', 'low')
print(df)

Task 46:
    A   B   C
0  10  35  25
1  20  35  25
2  30  35  25
3  40  35  25
    A   B   C logic
0  10  35  25   low
1  20  35  25   low
2  30  35  25  High
3  40  35  25  High


In [215]:
print('Task 47:')
marks_df = pd.DataFrame({
    'Language' : [56, 34, 78, 4], 
    'Math' : [80, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df['language_grade'] = np.where(marks_df['Language'] >= 50, 'Pass', 'Fail')
marks_df['math_grade'] = np.where(marks_df['Math'] >= 50, 'Pass', 'Fail')
marks_df['science_grade'] = np.where(marks_df['Science'] >= 50, 'Pass', 'Fail')
print(marks_df)

Task 47:
   Language  Math  Science
0        56    80       45
1        34    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science language_grade math_grade science_grade
0        56    80       45           Pass       Pass          Fail
1        34    80       90           Fail       Pass          Pass
2        78    23       95           Pass       Fail          Pass
3         4    60       20           Fail       Pass          Fail


In [217]:
print('Task 48:')  
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_language = marks_df[marks_df.Language >=40 ]
print(marks_df_passed_in_language)

Task 48:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95


In [218]:
print('Task 49:')  
marks_df_passed_in_lang_math = marks_df[(marks_df.Language >=50) & (marks_df.Math >= 50)]
print(marks_df_passed_in_lang_math)

Task 49:
   Language  Math  Science
0        60    90       45


In [219]:
print('Task 50:')  
marks_df_passed_in_lang_and_sc = marks_df.loc[(marks_df.Language >=50) & (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_and_sc)

Task 50:
   Language  Math  Science
2        78    23       95


In [221]:
print('Task 51:')
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
names = ['dhanush', 'simbu', 'kamal', 'vikram']
df = pd.DataFrame(data=stars, index=[names])
print(df)

Task 51:
         age  movies  awards
dhanush   31      51      42
simbu     23      23      12
kamal     65      87       4
vikram    50     200      78


In [226]:
print('Task 52:')
print(df.iloc[0:3])

Task 52:
         age  movies  awards
dhanush   31      51      42
simbu     23      23      12
kamal     65      87       4


In [228]:
print('Task 53:')  
numbers = pd.DataFrame({
        'one' : [31, 23, 65, 50],
        'two' : [51, 23, 87, 200]
    },
    index = [12, 14, 16, 18])
print(numbers)

print('label between 12 and 16')
print(numbers.loc[12:16])

print('index between 1 and 3')
print(numbers.iloc[1:3])


Task 53:
    one  two
12   31   51
14   23   23
16   65   87
18   50  200
label between 12 and 16
    one  two
12   31   51
14   23   23
16   65   87
index between 1 and 3
    one  two
14   23   23
16   65   87


In [230]:
print('Task 55:')
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
names = ['dhanush', 'simbu', 'kamal', 'vikram']
df = pd.DataFrame(data=stars, index=[names])
print(df[(df.movies>25)&(df.age>25)])

Task 51:
         age  movies  awards
dhanush   31      51      42
kamal     65      87       4
vikram    50     200      78


In [233]:
print('Task 56:')  
custom_stars = df[df.age.isin([31, 65])]
print(custom_stars)

Task 56:
         age  movies  awards
dhanush   31      51      42
kamal     65      87       4


In [234]:
print('Task 57:')  
print(numbers)
print(numbers[~( (numbers.one > 45) & (numbers.two < 50) )])

Task 57:
    one  two
12   31   51
14   23   23
16   65   87
18   50  200
    one  two
12   31   51
14   23   23
16   65   87
18   50  200


In [240]:
print('Task 58:')
def GrowUp(x):
    avg_weight =  sum(x[x['size'] =='S'].weight * 1.5)
    avg_weight += sum(x[x['size'] == 'M'].weight * 1.25)
    avg_weight += sum(x[x['size'] == 'L'].weight)
    avg_weight /= len(x)
    return pd.Series(['S',avg_weight,True], index=['size', 'weight', 'adult'])

animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})

gb = animals_df.groupby(['animal'])

expected_df = gb.apply(GrowUp)
print(expected_df)


Task 58:
       size   weight  adult
animal                     
cat       S  12.4375   True
dog       S  20.0000   True
fish      S   1.2500   True


In [243]:
print('Task 59:')
weights = animals_df.groupby(['weight']).get_group(12)  
print(weights)

Task 59:
  animal size  weight  adult
5    cat    L      12   True
6    cat    L      12   True


In [253]:
print('Task 60:')
sides_df = pd.DataFrame({
    'a' : [1, 1, 2, 4],
    'b' : [2, 1, 5, 4]
    })  
print(sides_df)
source_cols = sides_df.columns
print(source_cols)
new_cols = [str(x)+"_side" for x in source_cols]
side_category = {
    1 : 'North',
    2 : 'East',
    3 : 'South', 
    4 : 'West'
    }
# applymap takes  the input of each element and then maps with the corresponding value
#sides_df[new_cols] = sides_df[source_cols].applymap(side_category.get)
sides_df['side_a'] = sides_df['a'].map(side_category)
print(sides_df[source_cols])
print(sides_df)

Task 60:
   a  b
0  1  2
1  1  1
2  2  5
3  4  4
Index(['a', 'b'], dtype='object')
   a  b
0  1  2
1  1  1
2  2  5
3  4  4
   a  b side_a
0  1  2  North
1  1  1  North
2  2  5   East
3  4  4   West


In [255]:
print('Task 61:')  
df = pd.DataFrame({'A' : [1, 1, 2, 2], 'B' : [1, -1, 1, 2]})
print(df)

gb = df.groupby('A')

def replace(g):
    mask = g < 0
    g.loc[mask] = g[~mask].mean()
    print(g)
    return g

gbt = df.transform(replace)

print(gbt)

Task 61:
   A  B
0  1  1
1  1 -1
2  2  1
3  2  2
0    1.0
1    1.0
2    2.0
3    2.0
Name: A, dtype: float64
0    1.000000
1    1.333333
2    1.000000
3    2.000000
Name: B, dtype: float64
     A         B
0  1.0  1.000000
1  1.0  1.333333
2  2.0  1.000000
3  2.0  2.000000


In [274]:
print('Task 62:') 
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_lang_or_sc = marks_df.loc[(marks_df.Language >=50) | (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_or_sc)

Task 62:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95


In [261]:
print('Task 60:')
sides_df = pd.DataFrame({
    0 : [1, 1, 2, 4],
    1 : [2, 1, 5, 4]
    })  
print(sides_df)

Task 60:
   0  1
0  1  2
1  1  1
2  2  5
3  4  4


In [275]:
print('Task 63:')  
marks_df['pass1sub'] = 'Fail' 
print(marks_df)
marks_df.loc[(marks_df.Language >=45) , 'pass1sub'] = 'pass'
print(marks_df)

Task 63:
   Language  Math  Science pass1sub
0        60    90       45     Fail
1        45    80       90     Fail
2        78    23       95     Fail
3         4    60       20     Fail
   Language  Math  Science pass1sub
0        60    90       45     pass
1        45    80       90     pass
2        78    23       95     pass
3         4    60       20     Fail


In [319]:
print('Task 64:')  
df = pd.DataFrame({
    "a": np.random.randint(0, 100, size=(5,)), 
    "b": np.random.randint(0, 70, size=(5,))
})
print(df)
par = 65
print('with argsort')
df1 = df.loc[(df.a-2).abs().argsort()]
print(df1)
print(df.loc[(df.b-2).abs().argsort()])

Task 64:
    a   b
0   0   3
1  62  54
2  41  65
3  77  18
4  99  52
with argsort
    a   b
0   0   3
2  41  65
1  62  54
3  77  18
4  99  52
    a   b
0   0   3
3  77  18
4  99  52
1  62  54
2  41  65


In [323]:
print('Task 65:')  
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [2, 3, 90, 45, 34, 2] 
})
stars['agemod'] = (stars.age-50).abs()
print(stars.loc[stars['agemod'].argsort()])

Task 65:
   age  movies  agemod
1   50       3       0
3   45      45       5
4   65      34      15
2   24      90      26
5   18       2      32
0   17       2      33


In [324]:
print('Task 66:')  
print(stars.loc[(stars.age - 17).abs().argsort()])

Task 66:
   age  movies  agemod
0   17       2      33
5   18       2      32
2   24      90      26
3   45      45       5
1   50       3       0
4   65      34      15


In [326]:
print('Task 67:')
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [22, 33, 90, 75, 34, 2] 
})  
print(stars)
print('Young and more movies acted')
young = stars.age < 30    
more_movies = stars.movies > 30
young_more = [young, more_movies]
print(young_more)
young_more_Criteria = functools.reduce(lambda x, y : x & y, young_more)
print(stars[young_more_Criteria])

Task 67:
   age  movies
0   17      22
1   50      33
2   24      90
3   45      75
4   65      34
5   18       2
Young and more movies acted
[0     True
1    False
2     True
3    False
4    False
5     True
Name: age, dtype: bool, 0    False
1     True
2     True
3     True
4     True
5    False
Name: movies, dtype: bool]
   age  movies
2   24      90


In [329]:
print('Task 68:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
print('Young, Higher Salary, and Higher Position')
young = employees.age < 30
high_salary = employees.salary > 60
high_position = employees.grade > 6
young_salary_position = [young, high_salary, high_position]
young_salary_position_Criteria = functools.reduce(lambda x, y  :x & y, young_salary_position)
print(employees[young_salary_position_Criteria])

Task 68:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
Young, Higher Salary, and Higher Position
   age  salary  grade
0   17      75      7
2   24      90      9
5   18      78      8


In [3]:
print('Task 69:')  
import pandas as pd
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.rename(columns={'age': 'Age', 'salary': 'Salary'}, inplace=True)
print(employees)

Task 69:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   Age  Salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8


In [9]:
print('Task 70:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randint(1,10,size=len(employees)))
print(employees)

Task 70:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade  group
0   17      75      7      8
1   50      33      8      7
2   24      90      9      1
3   45     175      2      4
4   65     134      7      3
5   18      78      8      9


In [10]:
print('Task 71:')
employees.drop(employees.columns[[0]],axis =1 ,inplace =True)
print(employees)

Task 71:
   salary  grade  group
0      75      7      8
1      33      8      7
2      90      9      1
3     175      2      4
4     134      7      3
5      78      8      9


In [11]:
print('Task 72:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.drop(employees.columns[[0,1]],axis =1 ,inplace =True)
print(employees)

Task 70:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   grade
0      7
1      8
2      9
3      2
4      7
5      8


In [15]:
print('Task 73:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randint(1,10,size=len(employees)))
print(employees)
employees.drop(employees.columns[[0,len(employees.columns)-1]],axis=1,inplace =True)
print(employees)

Task 73:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade  group
0   17      75      7      9
1   50      33      8      5
2   24      90      9      5
3   45     175      2      8
4   65     134      7      4
5   18      78      8      6
   salary  grade
0      75      7
1      33      8
2      90      9
3     175      2
4     134      7
5      78      8


In [19]:
print('Task 74:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
group = employees.pop(employees.columns[0])
print(employees)
print(group)

Task 74:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   salary  grade  group
0      75      7      1
1      33      8      1
2      90      9      2
3     175      2      2
4     134      7      2
5      78      8      1
0    17
1    50
2    24
3    45
4    65
5    18
Name: age, dtype: int64


In [27]:
print('Task 76,77,78:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees) 
list1 = (employees.columns)
print(list1)
#array
list2=employees.values
print(list2)
#list
list3=employees.values.tolist()
print(list3)
print(list2.shape)

Task 76,77,78:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
Index(['age', 'salary', 'grade', 'group'], dtype='object')
[[ 17  75   7   1]
 [ 50  33   8   1]
 [ 24  90   9   2]
 [ 45 175   2   2]
 [ 65 134   7   2]
 [ 18  78   8   1]]
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
(6, 4)


In [30]:
print('Task 81')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
employees.drop_duplicates('group',inplace = True ,keep = 'last')
print(employees)

Task 76,77,78:
   age  salary  grade  group
4   65     134      7      2
5   18      78      8      1


In [33]:
print('Task 82:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users[['id', 'city']]
print(users1)
columns = ['id','count']
users1 = pd.DataFrame(users,columns=columns)
print(users1)

Task 82:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city
0   1   Toronto
1   1  Montreal
2   2   Calgary
3   2  Montreal
4   3  Montreal
5   3    Ottawa
   id  count
0   1      7
1   1      8
2   2      9
3   2      2
4   3      7
5   3      8


In [38]:
print('Task 84')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
emp =employees.iloc[0:2,1:3]
              
print(emp)

Task 81
   salary  grade
0      75      7
1      33      8


In [41]:
print('Task 85:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for index, row in users.iterrows():
    #print(row['city'], "==>", row['count'])
    print(row)

Task 85:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
id             1
city     Toronto
count          7
Name: 0, dtype: object
id              1
city     Montreal
count           8
Name: 1, dtype: object
id             2
city     Calgary
count          9
Name: 2, dtype: object
id              2
city     Montreal
count           2
Name: 3, dtype: object
id              3
city     Montreal
count           7
Name: 4, dtype: object
id            3
city     Ottawa
count         8
Name: 5, dtype: object


In [50]:
print('Task 86:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for row in users.itertuples(index=True, name='Pandas'):
    print(getattr(row, 'city'))
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row.count)
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row)    

Task 86:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto
Montreal
Calgary
Montreal
Montreal
Ottawa
7
8
9
2
7
8
Pandas(Index=0, id=1, city='Toronto', count=7)
Pandas(Index=1, id=1, city='Montreal', count=8)
Pandas(Index=2, id=2, city='Calgary', count=9)
Pandas(Index=3, id=2, city='Montreal', count=2)
Pandas(Index=4, id=3, city='Montreal', count=7)
Pandas(Index=5, id=3, city='Ottawa', count=8)


In [53]:
print('Task 87:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for i, row in users.iterrows():
    print(row)
    for j, col in row.items():    
        print(col)

Task 87:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
id             1
city     Toronto
count          7
Name: 0, dtype: object
1
Toronto
7
id              1
city     Montreal
count           8
Name: 1, dtype: object
1
Montreal
8
id             2
city     Calgary
count          9
Name: 2, dtype: object
2
Calgary
9
id              2
city     Montreal
count           2
Name: 3, dtype: object
2
Montreal
2
id              3
city     Montreal
count           7
Name: 4, dtype: object
3
Montreal
7
id            3
city     Ottawa
count         8
Name: 5, dtype: object
3
Ottawa
8
