In [6]:
import numpy as np
import numpy
import pandas as pd
import pandas

In [3]:
print('Task 1:')  
print(pd.__version__)

Task 1:
1.5.2


In [10]:
print('Task 2:')
dtype = [('col1','int32'), ('col2','float32'), ('col3','float32')]
#dtype shows the desired array type
values = numpy.zeros(20, dtype=dtype)
print(values)
index = ['Row_'+str(i) for i in range(1, len(values)+1)]
print(index)

df = pandas.DataFrame(values, index=index)
print(df)

df = pandas.DataFrame(values)
print(df)

Task 2:
[(0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.)]
['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5', 'Row_6', 'Row_7', 'Row_8', 'Row_9', 'Row_10', 'Row_11', 'Row_12', 'Row_13', 'Row_14', 'Row_15', 'Row_16', 'Row_17', 'Row_18', 'Row_19', 'Row_20']
        col1  col2  col3
Row_1      0   0.0   0.0
Row_2      0   0.0   0.0
Row_3      0   0.0   0.0
Row_4      0   0.0   0.0
Row_5      0   0.0   0.0
Row_6      0   0.0   0.0
Row_7      0   0.0   0.0
Row_8      0   0.0   0.0
Row_9      0   0.0   0.0
Row_10     0   0.0   0.0
Row_11     0   0.0   0.0
Row_12     0   0.0   0.0
Row_13     0   0.0   0.0
Row_14     0   0.0   0.0
Row_15     0   0.0   0.0
Row_16     0   0.0   0.0
Row_17     0   0.0   0.0
Row_18     0   0.0   0.0
Row_19     0   0.0   0.0
Row_20     0   0.0   0.0
    col1  col2  col3
0      0 

In [12]:
print('Task 3:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.iloc[:4]) 

Task 3:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0


In [21]:
print('Task 4:')
values = np.random.randint(150, 210, size=6)
print(values)

Task 4:
[186 208 168 152 157 185]


In [27]:
print('task 5:')
values = np.random.randint(10, 30,size = (4,2))
dataframe = pd.DataFrame(values,columns=list('AB'))
print(dataframe)

task 5:
    A   B
0  16  19
1  10  26
2  14  21
3  14  27


In [32]:
print('Task 6:')
values =np.random.randint(120, 340, size=(5, 4))
dataframe = pd.DataFrame(values, columns=['A', 'B', 'C', 'D'])
print(dataframe)

Task 6:
     A    B    C    D
0  120  329  315  142
1  121  329  212  183
2  186  248  283  339
3  191  309  122  324
4  168  206  338  265


In [34]:
print("task 7")
values = np.random.randint(1,100,size =(4,5))
print(values)

task 7
[[ 5 78 20 99 22]
 [38 53 77 87 56]
 [11 90 23 17 87]
 [25 64 16 87 57]]


In [38]:
print ("task 8")
values = np.random.randint(100,size = (2,5))
df = pd.DataFrame(values ,columns =list('ABCDE'))
print(df)

task 8
    A   B   C   D   E
0  58  55  86  76  80
1  95  55  34  52  19


In [43]:
print("task 9"),
values = np.zeros((3,2))
df = pd.DataFrame(values ,columns = list('xy'))
print(df)

task 9
     x    y
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0


In [53]:
print("task 10")
dtype = [('math','int32'),('science','int32')]
values = np.random.randint(50,100,size =(10,2))
index = [dtype[i][0] for i  in range(len(dtype))]
print(index)
df =pd.DataFrame(values,columns = index)
print(df)

task 10
['math', 'science']
   math  science
0    99       54
1    94       57
2    69       55
3    87       76
4    96       88
5    55       50
6    88       67
7    79       84
8    93       74
9    50       92


In [54]:
print('Task 11:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.head())

Task 11:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0
4  8  6    mar  fri  91.7  33.3   77.5    9   8.3  97     4   0.2     0


In [57]:
print('Task 13:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0:4,0:5])


Task 13:
   0  1      2    3     4
0  X  Y  month  day  FFMC
1  7  5    mar  fri  86.2
2  7  4    oct  tue  90.6
3  7  4    oct  sat  90.6


In [60]:
print('Task 14:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0::2,0:5])

Task 14:
     0  1      2    3     4
0    X  Y  month  day  FFMC
2    7  4    oct  tue  90.6
4    8  6    mar  fri  91.7
6    8  6    aug  sun  92.3
8    8  6    aug  mon  91.5
..  .. ..    ...  ...   ...
508  2  4    aug  fri    91
510  5  4    aug  fri    91
512  8  6    aug  sun  81.6
514  2  4    aug  sun  81.6
516  1  4    aug  sat  94.4

[259 rows x 5 columns]


In [74]:
print('Task 15:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
print(df1)
df['total'] = df1.sum(axis=1)
print(df)

Task 14:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
   language  science  maths  history
0        90       56     34       34
1        10       34     32       67
2        90       23     12       32
3        20       67     90       45
4        30       56     45       65
5        90       45     45       34
6        50       90     45       23
  student  language  science  maths  history  total
0   kumar        90       56     34       34    214
1   kevin        10       34     32       67    143
2   sammy        90       23     12       32    157
3  janice        20       67     90       45    222
4   peter        30       56     45       65    196
5    prem        90    

In [76]:
print('Task 16:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df[df.maths>40]
print(df1)

Task 14:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [80]:
print('Task 17:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.query('language>=50')
print(df1)

Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
2   sammy        90       23     12       32
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [81]:
print('Task 18:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df)


Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4    prem        90       45     45       34
5  carrol        50       90     45       23


In [82]:
print('Task 19:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [1,2,5])
print(df)


Task 17:
  student  language  science  maths  history
0   sammy        90       23     12       32
1  janice        20       67     90       45
2    prem        90       45     45       34
3  carrol        50       90     45       23


In [83]:
print('Task 20:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df.columns[3])


Task 17:
maths


In [84]:
print('Task 21:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [0])
print(df)

Task 18:
    kumar  90  56  34  34.1
0   kevin  10  34  32    67
1   sammy  90  23  12    32
2  janice  20  67  90    45
3   peter  30  56  45    65
4    prem  90  45  45    34
5  carrol  50  90  45    23


In [90]:
print('Task 22:')
from io import StringIO

s = """
        X,Y
        10, 21
        32, 44
        52, 63
    """

df = pd.read_csv(StringIO(s))

print(df.shape)
print(df)

Task 22:
(3, 2)
           X   Y
0         10  21
1         32  44
2         52  63
