In [6]:
import numpy as np
import numpy
import pandas as pd
import pandas

In [3]:
print('Task 1:')  
print(pd.__version__)

Task 1:
1.5.2


In [10]:
print('Task 2:')
dtype = [('col1','int32'), ('col2','float32'), ('col3','float32')]
#dtype shows the desired array type
values = numpy.zeros(20, dtype=dtype)
print(values)
index = ['Row_'+str(i) for i in range(1, len(values)+1)]
print(index)

df = pandas.DataFrame(values, index=index)
print(df)

df = pandas.DataFrame(values)
print(df)

Task 2:
[(0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.) (0, 0., 0.)
 (0, 0., 0.) (0, 0., 0.)]
['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5', 'Row_6', 'Row_7', 'Row_8', 'Row_9', 'Row_10', 'Row_11', 'Row_12', 'Row_13', 'Row_14', 'Row_15', 'Row_16', 'Row_17', 'Row_18', 'Row_19', 'Row_20']
        col1  col2  col3
Row_1      0   0.0   0.0
Row_2      0   0.0   0.0
Row_3      0   0.0   0.0
Row_4      0   0.0   0.0
Row_5      0   0.0   0.0
Row_6      0   0.0   0.0
Row_7      0   0.0   0.0
Row_8      0   0.0   0.0
Row_9      0   0.0   0.0
Row_10     0   0.0   0.0
Row_11     0   0.0   0.0
Row_12     0   0.0   0.0
Row_13     0   0.0   0.0
Row_14     0   0.0   0.0
Row_15     0   0.0   0.0
Row_16     0   0.0   0.0
Row_17     0   0.0   0.0
Row_18     0   0.0   0.0
Row_19     0   0.0   0.0
Row_20     0   0.0   0.0
    col1  col2  col3
0      0 

In [12]:
print('Task 3:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.iloc[:4]) 

Task 3:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0


In [21]:
print('Task 4:')
values = np.random.randint(150, 210, size=6)
print(values)

Task 4:
[186 208 168 152 157 185]


In [27]:
print('task 5:')
values = np.random.randint(10, 30,size = (4,2))
dataframe = pd.DataFrame(values,columns=list('AB'))
print(dataframe)

task 5:
    A   B
0  16  19
1  10  26
2  14  21
3  14  27


In [32]:
print('Task 6:')
values =np.random.randint(120, 340, size=(5, 4))
dataframe = pd.DataFrame(values, columns=['A', 'B', 'C', 'D'])
print(dataframe)

Task 6:
     A    B    C    D
0  120  329  315  142
1  121  329  212  183
2  186  248  283  339
3  191  309  122  324
4  168  206  338  265


In [34]:
print("task 7")
values = np.random.randint(1,100,size =(4,5))
print(values)

task 7
[[ 5 78 20 99 22]
 [38 53 77 87 56]
 [11 90 23 17 87]
 [25 64 16 87 57]]


In [38]:
print ("task 8")
values = np.random.randint(100,size = (2,5))
df = pd.DataFrame(values ,columns =list('ABCDE'))
print(df)

task 8
    A   B   C   D   E
0  58  55  86  76  80
1  95  55  34  52  19


In [43]:
print("task 9"),
values = np.zeros((3,2))
df = pd.DataFrame(values ,columns = list('xy'))
print(df)

task 9
     x    y
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0


In [53]:
print("task 10")
dtype = [('math','int32'),('science','int32')]
values = np.random.randint(50,100,size =(10,2))
index = [dtype[i][0] for i  in range(len(dtype))]
print(index)
df =pd.DataFrame(values,columns = index)
print(df)

task 10
['math', 'science']
   math  science
0    99       54
1    94       57
2    69       55
3    87       76
4    96       88
5    55       50
6    88       67
7    79       84
8    93       74
9    50       92


In [54]:
print('Task 11:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.head())

Task 11:
  0  1      2    3     4     5      6    7     8   9     10    11    12
0  X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
1  7  5    mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7     0     0
2  7  4    oct  tue  90.6  35.4  669.1  6.7    18  33   0.9     0     0
3  7  4    oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3     0     0
4  8  6    mar  fri  91.7  33.3   77.5    9   8.3  97     4   0.2     0


In [57]:
print('Task 13:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0:4,0:5])


Task 13:
   0  1      2    3     4
0  X  Y  month  day  FFMC
1  7  5    mar  fri  86.2
2  7  4    oct  tue  90.6
3  7  4    oct  sat  90.6


In [60]:
print('Task 14:') 
df = pandas.read_csv('forestfires.csv', sep=',', header=None)

print(df.iloc[0::2,0:5])

Task 14:
     0  1      2    3     4
0    X  Y  month  day  FFMC
2    7  4    oct  tue  90.6
4    8  6    mar  fri  91.7
6    8  6    aug  sun  92.3
8    8  6    aug  mon  91.5
..  .. ..    ...  ...   ...
508  2  4    aug  fri    91
510  5  4    aug  fri    91
512  8  6    aug  sun  81.6
514  2  4    aug  sun  81.6
516  1  4    aug  sat  94.4

[259 rows x 5 columns]


In [74]:
print('Task 15:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
print(df1)
df['total'] = df1.sum(axis=1)
print(df)

Task 14:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
   language  science  maths  history
0        90       56     34       34
1        10       34     32       67
2        90       23     12       32
3        20       67     90       45
4        30       56     45       65
5        90       45     45       34
6        50       90     45       23
  student  language  science  maths  history  total
0   kumar        90       56     34       34    214
1   kevin        10       34     32       67    143
2   sammy        90       23     12       32    157
3  janice        20       67     90       45    222
4   peter        30       56     45       65    196
5    prem        90    

In [76]:
print('Task 16:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df[df.maths>40]
print(df1)

Task 14:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [80]:
print('Task 17:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.query('language>=50')
print(df1)

Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
2   sammy        90       23     12       32
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [81]:
print('Task 18:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df)


Task 17:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4    prem        90       45     45       34
5  carrol        50       90     45       23


In [82]:
print('Task 19:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [1,2,5])
print(df)


Task 17:
  student  language  science  maths  history
0   sammy        90       23     12       32
1  janice        20       67     90       45
2    prem        90       45     45       34
3  carrol        50       90     45       23


In [83]:
print('Task 20:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [5])
print(df.columns[3])


Task 17:
maths


In [84]:
print('Task 21:') 
df = pandas.read_csv('abc.csv', sep=',',skiprows = [0])
print(df)

Task 18:
    kumar  90  56  34  34.1
0   kevin  10  34  32    67
1   sammy  90  23  12    32
2  janice  20  67  90    45
3   peter  30  56  45    65
4    prem  90  45  45    34
5  carrol  50  90  45    23


In [91]:
print('Task 22:')
from io import StringIO

s = """
        X,Y,Z
        10, 21,23
        32, 44,34
        52, 63,56
    """

df = pd.read_csv(StringIO(s))

print(df.shape)
print(df)

Task 22:
(3, 3)
           X   Y   Z
0         10  21  23
1         32  44  34
2         52  63  56


In [100]:
print('Task 23:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)
print(df)
df['min']= df1.min(axis=1)
print(df)
df['sum'] = df1.sum(axis=1)
print(df)
df['average'] = df1.mean(axis=1).astype(int)
print(df)

Task 23:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max
0   kumar        90       56     34       34   90
1   kevin        10       34     32       67   67
2   sammy        90       23     12       32   90
3  janice        20       67     90       45   90
4   peter        30       56     45       65   65
5    prem        90       45     45       34   90
6  carrol        50       90     45       23   90
  student  language  science  maths  history  max  min
0   kumar        90       56     34       34   90   34
1   kevin        10       34     32       67   67   10
2   sammy        90       23     12       32   90   12
3  janice  

In [103]:
print('Task 24:') 
df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)

df['min']= df1.min(axis=1)

df['sum'] = df1.sum(axis=1)
df['average'] = df1.mean(axis=1).astype(int)
def math1(row):
    return (row.maths*2)
df['math_special'] = df1.apply(math1,axis=1).astype(int)
print(df)

Task 23:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max  min  sum  average  \
0   kumar        90       56     34       34   90   34  214       53   
1   kevin        10       34     32       67   67   10  143       35   
2   sammy        90       23     12       32   90   12  157       39   
3  janice        20       67     90       45   90   20  222       55   
4   peter        30       56     45       65   65   30  196       49   
5    prem        90       45     45       34   90   34  214       53   
6  carrol        50       90     45       23   90   23  208       52   

   math_special  
0            68  
1            64  


In [118]:
print('Task 25:') 
def pass_one_subject(row):
    if(row.maths >=45):
        return 'Pass'
    if(row.language > 40 and row.science > 44):
        return 'Pass'
    
    return 'Fail' 

df = pandas.read_csv('abc.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis=1)
df['max']= df1.max(axis=1)

df['min']= df1.min(axis=1)

df['sum'] = df1.sum(axis=1)
df['average'] = df1.mean(axis=1).astype(int)
def math1(row):
    return (row.maths*2)
#function will return string 
df['pass'] = df1.apply(pass_one_subject,axis=1)
print(df)


Task 25:
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  max  min  sum  average  pass
0   kumar        90       56     34       34   90   34  214       53  Pass
1   kevin        10       34     32       67   67   10  143       35  Fail
2   sammy        90       23     12       32   90   12  157       39  Fail
3  janice        20       67     90       45   90   20  222       55  Pass
4   peter        30       56     45       65   65   30  196       49  Pass
5    prem        90       45     45       34   90   34  214       53  Pass
6  carrol        50       90     45       23   90   23  208       52  Pass


In [110]:
print('Task 26:') 
df = pandas.read_csv('abc2.csv', sep=',')
print(df)
df1 = df.drop(['student'],axis =1)
df.fillna(df1.mean(),inplace =True)
print(df)


Task 26:
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0    NaN       34
6  carrol        50     90.0   45.0       23
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10     54.0   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20     54.0   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0   43.0       34
6  carrol        50     90.0   45.0       23


In [116]:
print('Task 27:')
df = pd.DataFrame(np.random.randint(20 ,40, size=(10,5)))
df.iloc[0::2, 0:2] = np.nan 
print(df)
df.loc[:, 'test'] = df.iloc[:, 2:].sum(axis=1)
print(df)

Task 27:
      0     1   2   3   4
0   NaN   NaN  35  26  29
1  23.0  21.0  36  35  39
2   NaN   NaN  32  38  27
3  27.0  26.0  25  21  33
4   NaN   NaN  20  21  22
5  25.0  24.0  38  26  20
6   NaN   NaN  37  26  30
7  38.0  29.0  35  20  29
8   NaN   NaN  27  30  31
9  28.0  24.0  30  31  33
      0     1   2   3   4  test
0   NaN   NaN  35  26  29    90
1  23.0  21.0  36  35  39   110
2   NaN   NaN  32  38  27    97
3  27.0  26.0  25  21  33    79
4   NaN   NaN  20  21  22    63
5  25.0  24.0  38  26  20    84
6   NaN   NaN  37  26  30    93
7  38.0  29.0  35  20  29    84
8   NaN   NaN  27  30  31    88
9  28.0  24.0  30  31  33    94


In [117]:
print('Task 28:') 
df = pandas.read_csv('score.csv', sep=',', encoding = "ISO-8859-1")
print(df.shape) 

Task 28:
(16, 5)


In [134]:
print('Task 29:')
df = pd.DataFrame(np.random.randint(20 ,40, size=(10,5)),columns=list('ABCDE'))
print(df)
df.iloc[0::2, 0:2] = np.nan 
print(df)
#inplace == True it changes the original dataframe
df1=df.fillna(df.mean() ,inplace =False)
print(df1)
print(df)


Task 29:
    A   B   C   D   E
0  24  26  30  22  22
1  22  22  27  23  29
2  35  34  39  22  25
3  33  25  37  20  21
4  24  22  26  36  28
5  21  26  27  39  39
6  36  20  30  38  29
7  29  26  34  32  30
8  39  39  22  23  34
9  34  28  39  31  20
      A     B   C   D   E
0   NaN   NaN  30  22  22
1  22.0  22.0  27  23  29
2   NaN   NaN  39  22  25
3  33.0  25.0  37  20  21
4   NaN   NaN  26  36  28
5  21.0  26.0  27  39  39
6   NaN   NaN  30  38  29
7  29.0  26.0  34  32  30
8   NaN   NaN  22  23  34
9  34.0  28.0  39  31  20
      A     B   C   D   E
0  27.8  25.4  30  22  22
1  22.0  22.0  27  23  29
2  27.8  25.4  39  22  25
3  33.0  25.0  37  20  21
4  27.8  25.4  26  36  28
5  21.0  26.0  27  39  39
6  27.8  25.4  30  38  29
7  29.0  26.0  34  32  30
8  27.8  25.4  22  23  34
9  34.0  28.0  39  31  20
      A     B   C   D   E
0   NaN   NaN  30  22  22
1  22.0  22.0  27  23  29
2   NaN   NaN  39  22  25
3  33.0  25.0  37  20  21
4   NaN   NaN  26  36  28
5  21.0  26.0  27  39

In [141]:
print('Task 30:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df[-4:])

Task 30:
    0  1    2    3     4     5      6     7     8   9    10 11     12
514  2  4  aug  sun  81.6  56.7  665.6   1.9  21.9  71  5.8  0  54.29
515  7  4  aug  sun  81.6  56.7  665.6   1.9  21.2  70  6.7  0  11.16
516  1  4  aug  sat  94.4   146  614.7  11.3  25.6  42    4  0      0
517  6  3  nov  tue  79.5     3  106.7   1.1  11.8  31  4.5  0      0


In [139]:
print('Task 31:')
import functools
series1 = pd.Series([i / 100.0 for i in range(1,6)])
print(series1)
def CumRet(x,y):
    return x +(1 + y)
def Red(x):
    return functools.reduce(CumRet,x,1.0)
s2 = series1.expanding().apply(Red)

print(s2)

Task 31:
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    2.01
1    3.03
2    4.06
3    5.10
4    6.15
dtype: float64


In [145]:
print('Task 32:')
df = pandas.read_csv('forestfires.csv', sep=',')
print(df[-4:-1])

Task 30:
     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00


In [143]:
print('Task 33:')
df = pandas.read_csv('forestfires.csv', sep=',')
print(df[2:4])

Task 30:
   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0


In [146]:
print('Task 34:')
df = pandas.read_csv('forestfires.csv', sep=',', header=None)
print(df.iloc[1:9])

Task 34:
  0  1    2    3     4      5      6     7     8   9    10   11 12
1  7  5  mar  fri  86.2   26.2   94.3   5.1   8.2  51  6.7    0  0
2  7  4  oct  tue  90.6   35.4  669.1   6.7    18  33  0.9    0  0
3  7  4  oct  sat  90.6   43.7  686.9   6.7  14.6  33  1.3    0  0
4  8  6  mar  fri  91.7   33.3   77.5     9   8.3  97    4  0.2  0
5  8  6  mar  sun  89.3   51.3  102.2   9.6  11.4  99  1.8    0  0
6  8  6  aug  sun  92.3   85.3    488  14.7  22.2  29  5.4    0  0
7  8  6  aug  mon  92.3   88.9  495.6   8.5  24.1  27  3.1    0  0
8  8  6  aug  mon  91.5  145.4  608.2  10.7     8  86  2.2    0  0


In [158]:
print('Task 36:')  
def xrange(x):
    return iter(range(x))
import random as rn
rnd_1  =  [ rn.randrange ( 1 , 200 )  for  _  in  range ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 200 )  for  _  in  range ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 200)  for  _ in  range ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'random_1' :  rnd_1 ,  'random_2' :  rnd_2 ,  'random_3' :  rnd_3 })

print(data)

Task 36:
1000
          date  random_1  random_2  random_3
0   2012-04-10       163        66        40
1   2012-04-11       151       185        85
2   2012-04-12       154       180        32
3   2012-04-13       134        81        32
4   2012-04-14       160       130       142
..         ...       ...       ...       ...
995 2014-12-31       105       120        34
996 2015-01-01        17       146       198
997 2015-01-02       120        64        67
998 2015-01-03       126        60        45
999 2015-01-04       195        56        28

[1000 rows x 4 columns]


In [159]:
print('Task 37:')
below_15 = data[data['random_1'] < 20]    
print(below_50)

Task 37:
          date  rnd_1  rnd_2  rnd_3
29  2012-05-09     17     50    143
52  2012-06-01     18     63    196
56  2012-06-05     18     29     69
64  2012-06-13      8    184    138
65  2012-06-14     16    142     16
..         ...    ...    ...    ...
966 2014-12-02     10    154    129
975 2014-12-11     12     67    177
979 2014-12-15     13     38     12
989 2014-12-25      7     65    110
999 2015-01-04      6    156     99

[93 rows x 4 columns]


In [162]:
five_to_ten = data[(data['random_1']>=5 )& (data['random_1']<10)]
print(five_to_ten) 

          date  random_1  random_2  random_3
55  2012-06-04         6       158       138
84  2012-07-03         5       122         2
101 2012-07-20         6       177       112
106 2012-07-25         5       124        48
112 2012-07-31         5       197        21
248 2012-12-14         6         8       150
267 2013-01-02         6       165        16
384 2013-04-29         5       134         9
385 2013-04-30         6        82       170
403 2013-05-18         8       136        88
408 2013-05-23         5        12       180
458 2013-07-12         6       138        30
475 2013-07-29         7       163        35
495 2013-08-18         5       143       116
513 2013-09-05         6       112       148
528 2013-09-20         8        86       124
538 2013-09-30         9       128        55
558 2013-10-20         7        48        86
583 2013-11-14         7        34         5
592 2013-11-23         8        37         7
599 2013-11-30         7        91       118
621 2013-1

In [163]:
print('Task 39:')  
fifteen_to_20 = data[(data['random_1']>=15 )& (data['random_1']<20)]
print(fifteen_to_20)

Task 39:
          date  random_1  random_2  random_3
58  2012-06-07        15        84       199
75  2012-06-24        19        16        22
151 2012-09-08        15        22        72
206 2012-11-02        18       187       163
207 2012-11-03        16       148        97
261 2012-12-27        15       110        60
296 2013-01-31        18       121        35
399 2013-05-14        15       128       187
432 2013-06-16        19       100       136
574 2013-11-05        17       143        42
629 2013-12-30        15        42        68
644 2014-01-14        17       197       156
760 2014-05-10        18       146       118
867 2014-08-25        19       166       100
920 2014-10-17        16        79        60
931 2014-10-28        17       146       132
996 2015-01-01        17       146       198


In [ ]:
print('Task 40:')  
fifteen_to_20 = data[(data['random_1']>=15 )& (data['random_1']<33)]
print(fifteen_to_20)